name: kitchensync
description: "KitchenSync App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  nfc_manager: ^3.3.0
  google_fonts: ^6.2.0
  flutter_floating_bottom_bar: ^1.2.0
  dot_navigation_bar: ^1.0.2
  floating_navbar: ^2.0.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/data/items.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Icon.png" 
