name: kitchensync
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1 

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  nfc_manager: ^3.3.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
